export const BTC_EXCHANGES = [
    { label: 'ArgenBTC', ticker: 'argenbtc' },
    { label: 'belo', ticker: 'belo' },
    { label: 'Binance P2P', ticker: 'binancep2p' },
    { label: 'Bitex', ticker: 'bitex' },
    { label: 'Bitmonedero', ticker: 'bitmonedero' },
    { label: 'Bitso', ticker: 'bitso' },
    { label: 'Buda', ticker: 'buda' },
    { label: 'Buenbit', ticker: 'buenbit' },
    { label: 'Calypso P2P', ticker: 'calypsop2p' },
    { label: 'Copter', ticker: 'copter' },
    { label: 'CryptoMarket', ticker: 'cryptomarket' },
    { label: 'Decrypto', ticker: 'decrypto' },
    { label: 'Fiwind', ticker: 'fiwind' },
    { label: 'Huobi P2P', ticker: 'huobip2p' },
    { label: 'Kripton Market', ticker: 'kriptonmarket' },
    { label: 'KuCoin P2P', ticker: 'kucoinp2p' },
    { label: 'Latamex', ticker: 'latamex' },
    { label: 'Lemon Cash', ticker: 'lemoncash' },
    { label: "Let'sBit", ticker: 'letsbit' },
    { label: 'LocalBitcoins P2P', ticker: 'localbitcoinsp2p' },
    { label: 'Paxful P2P', ticker: 'paxfulp2p' },
    { label: 'Ripio', ticker: 'ripio' },
    { label: 'Ripio Trade', ticker: 'ripiotrade' },
    { label: 'Saldo', ticker: 'saldo' },
    { label: 'SatoshiTango', ticker: 'satoshitango' },
    { label: 'TiendaCrypto', ticker: 'tiendacrypto' },
    { label: 'Calypso P2P', ticker: 'calypsop2p' },
    { label: 'Decrypto', ticker: 'decrypto' },
    { label: 'Fiwind', ticker: 'fiwind' },
    { label: 'TiendaCrypto', ticker: 'tiendacrypto' },
];
